/* DO NOT EDIT THIS FILE - it is machine generated */

#include <fmod.hpp>
#include <jni.h>
#include <jni.h>
#include <string>
#include <unistd.h>
#include <codecvt>

#include "../../../../../../../Library/Android/sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/jni.h"
/* Header for class com_zxh_voicechange_MainActivity */

#ifndef _Included_com_zxh_voicechange_MainActivity
#define _Included_com_zxh_voicechange_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_zxh_voicechange_MainActivity_VOICE_NORMAL
#define com_zxh_voicechange_MainActivity_VOICE_NORMAL 0L
#undef com_zxh_voicechange_MainActivity_VOICE_LUOLI
#define com_zxh_voicechange_MainActivity_VOICE_LUOLI 1L
#undef com_zxh_voicechange_MainActivity_VOICE_DASHU
#define com_zxh_voicechange_MainActivity_VOICE_DASHU 2L
#undef com_zxh_voicechange_MainActivity_VOICE_JINGSONG
#define com_zxh_voicechange_MainActivity_VOICE_JINGSONG 3L
#undef com_zxh_voicechange_MainActivity_VOICE_GAOGUAI
#define com_zxh_voicechange_MainActivity_VOICE_GAOGUAI 4L
#undef com_zxh_voicechange_MainActivity_VOICE_KONGLING
#define com_zxh_voicechange_MainActivity_VOICE_KONGLING 5L

#undef com_zxh_voicechange_MainActivity_VOICE_CUSTOM
#define com_zxh_voicechange_MainActivity_VOICE_CUSTOM 6L


/*
 * Class:     com_zxh_voicechange_MainActivity
 * Method:    playMusicVoiceNative
 * Signature: (Ljava/lang/String;I)V
 */

extern "C" JNIEXPORT void JNICALL Java_com_zxh_voicechange_MainActivity_playMusicVoiceNative
  (JNIEnv *, jobject, jstring, jint, jfloat pitch_value, jfloat echo_value, jfloat tremolo_value,
   jfloat frequency_value);


extern "C" JNIEXPORT void JNICALL Java_com_zxh_voicechange_MainActivity_pauseOtherVoice (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
